# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voos_service_pb2 as voos__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voos_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarVoos = channel.unary_unary(
                '/voos.VoosService/ConsultarVoos',
                request_serializer=voos__service__pb2.ConsultaVoosRequest.SerializeToString,
                response_deserializer=voos__service__pb2.ConsultaVoosResponse.FromString,
                _registered_method=True)
        self.MonitorarVoo = channel.unary_stream(
                '/voos.VoosService/MonitorarVoo',
                request_serializer=voos__service__pb2.MonitorarVooRequest.SerializeToString,
                response_deserializer=voos__service__pb2.StatusVooUpdate.FromString,
                _registered_method=True)
        self.ChatSuporte = channel.stream_stream(
                '/voos.VoosService/ChatSuporte',
                request_serializer=voos__service__pb2.ChatMessage.SerializeToString,
                response_deserializer=voos__service__pb2.ChatMessage.FromString,
                _registered_method=True)


class VoosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConsultarVoos(self, request, context):
        """1. Unary RPC - Consulta simples de voos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorarVoo(self, request, context):
        """2. Server Streaming RPC - Monitoramento de voo em tempo real
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatSuporte(self, request_iterator, context):
        """3. Bidirectional Streaming RPC - Chat de suporte
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarVoos': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarVoos,
                    request_deserializer=voos__service__pb2.ConsultaVoosRequest.FromString,
                    response_serializer=voos__service__pb2.ConsultaVoosResponse.SerializeToString,
            ),
            'MonitorarVoo': grpc.unary_stream_rpc_method_handler(
                    servicer.MonitorarVoo,
                    request_deserializer=voos__service__pb2.MonitorarVooRequest.FromString,
                    response_serializer=voos__service__pb2.StatusVooUpdate.SerializeToString,
            ),
            'ChatSuporte': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatSuporte,
                    request_deserializer=voos__service__pb2.ChatMessage.FromString,
                    response_serializer=voos__service__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voos.VoosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voos.VoosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarVoos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/voos.VoosService/ConsultarVoos',
            voos__service__pb2.ConsultaVoosRequest.SerializeToString,
            voos__service__pb2.ConsultaVoosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorarVoo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/voos.VoosService/MonitorarVoo',
            voos__service__pb2.MonitorarVooRequest.SerializeToString,
            voos__service__pb2.StatusVooUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatSuporte(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voos.VoosService/ChatSuporte',
            voos__service__pb2.ChatMessage.SerializeToString,
            voos__service__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
