# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voos_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voos_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12voos_service.proto\x12\x04voos\"\xa1\x02\n\x03Voo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06origem\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x17\n\x0fhorario_partida\x18\x05 \x01(\t\x12\x17\n\x0fhorario_chegada\x18\x06 \x01(\t\x12\r\n\x05preco\x18\x07 \x01(\x01\x12\x17\n\x0f\x63ompanhia_aerea\x18\x08 \x01(\t\x12\x12\n\nnumero_voo\x18\t \x01(\t\x12\x1c\n\x14\x61ssentos_disponiveis\x18\n \x01(\x05\x12\x0e\n\x06status\x18\x0b \x01(\t\x12\x18\n\x10\x63lasse_economica\x18\x0c \x01(\t\x12\x10\n\x08\x61\x65ronave\x18\r \x01(\t\x12\x17\n\x0f\x64uracao_minutos\x18\x0e \x01(\x05\"\x9a\x01\n\x13\x43onsultaVoosRequest\x12\x0e\n\x06origem\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x11\n\tpreco_max\x18\x04 \x01(\x01\x12\x17\n\x0f\x63ompanhia_aerea\x18\x05 \x01(\t\x12\x15\n\rfaixa_horario\x18\x06 \x01(\t\x12\x11\n\tordenacao\x18\x07 \x01(\t\"g\n\x14\x43onsultaVoosResponse\x12\x17\n\x04voos\x18\x01 \x03(\x0b\x32\t.voos.Voo\x12\x19\n\x11total_encontrados\x18\x02 \x01(\x05\x12\x1b\n\x13tempo_processamento\x18\x03 \x01(\t\")\n\x13MonitorarVooRequest\x12\x12\n\nnumero_voo\x18\x01 \x01(\t\"x\n\x0fStatusVooUpdate\x12\x12\n\nnumero_voo\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08mensagem\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x1c\n\x14progresso_percentual\x18\x05 \x01(\x05\"U\n\x0b\x43hatMessage\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x10\n\x08\x63ontexto\x18\x04 \x01(\t2\xd2\x01\n\x0bVoosService\x12\x46\n\rConsultarVoos\x12\x19.voos.ConsultaVoosRequest\x1a\x1a.voos.ConsultaVoosResponse\x12\x42\n\x0cMonitorarVoo\x12\x19.voos.MonitorarVooRequest\x1a\x15.voos.StatusVooUpdate0\x01\x12\x37\n\x0b\x43hatSuporte\x12\x11.voos.ChatMessage\x1a\x11.voos.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voos_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOO']._serialized_start=29
  _globals['_VOO']._serialized_end=318
  _globals['_CONSULTAVOOSREQUEST']._serialized_start=321
  _globals['_CONSULTAVOOSREQUEST']._serialized_end=475
  _globals['_CONSULTAVOOSRESPONSE']._serialized_start=477
  _globals['_CONSULTAVOOSRESPONSE']._serialized_end=580
  _globals['_MONITORARVOOREQUEST']._serialized_start=582
  _globals['_MONITORARVOOREQUEST']._serialized_end=623
  _globals['_STATUSVOOUPDATE']._serialized_start=625
  _globals['_STATUSVOOUPDATE']._serialized_end=745
  _globals['_CHATMESSAGE']._serialized_start=747
  _globals['_CHATMESSAGE']._serialized_end=832
  _globals['_VOOSSERVICE']._serialized_start=835
  _globals['_VOOSSERVICE']._serialized_end=1045
# @@protoc_insertion_point(module_scope)
