# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import voos_service_pb2 as voos__service__pb2


class VoosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsultarVoos = channel.unary_unary(
                '/voos.VoosService/ConsultarVoos',
                request_serializer=voos__service__pb2.ConsultaVoosRequest.SerializeToString,
                response_deserializer=voos__service__pb2.ConsultaVoosResponse.FromString,
                )


class VoosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConsultarVoos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsultarVoos': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarVoos,
                    request_deserializer=voos__service__pb2.ConsultaVoosRequest.FromString,
                    response_serializer=voos__service__pb2.ConsultaVoosResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voos.VoosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsultarVoos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/voos.VoosService/ConsultarVoos',
            voos__service__pb2.ConsultaVoosRequest.SerializeToString,
            voos__service__pb2.ConsultaVoosResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
