# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voos_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12voos_service.proto\x12\x04voos\"\xa1\x02\n\x03Voo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06origem\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x17\n\x0fhorario_partida\x18\x05 \x01(\t\x12\x17\n\x0fhorario_chegada\x18\x06 \x01(\t\x12\r\n\x05preco\x18\x07 \x01(\x01\x12\x17\n\x0f\x63ompanhia_aerea\x18\x08 \x01(\t\x12\x12\n\nnumero_voo\x18\t \x01(\t\x12\x1c\n\x14\x61ssentos_disponiveis\x18\n \x01(\x05\x12\x0e\n\x06status\x18\x0b \x01(\t\x12\x18\n\x10\x63lasse_economica\x18\x0c \x01(\t\x12\x10\n\x08\x61\x65ronave\x18\r \x01(\t\x12\x17\n\x0f\x64uracao_minutos\x18\x0e \x01(\x05\"\x9a\x01\n\x13\x43onsultaVoosRequest\x12\x0e\n\x06origem\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x11\n\tpreco_max\x18\x04 \x01(\x01\x12\x17\n\x0f\x63ompanhia_aerea\x18\x05 \x01(\t\x12\x15\n\rfaixa_horario\x18\x06 \x01(\t\x12\x11\n\tordenacao\x18\x07 \x01(\t\"g\n\x14\x43onsultaVoosResponse\x12\x17\n\x04voos\x18\x01 \x03(\x0b\x32\t.voos.Voo\x12\x19\n\x11total_encontrados\x18\x02 \x01(\x05\x12\x1b\n\x13tempo_processamento\x18\x03 \x01(\t2U\n\x0bVoosService\x12\x46\n\rConsultarVoos\x12\x19.voos.ConsultaVoosRequest\x1a\x1a.voos.ConsultaVoosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voos_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOO']._serialized_start=29
  _globals['_VOO']._serialized_end=318
  _globals['_CONSULTAVOOSREQUEST']._serialized_start=321
  _globals['_CONSULTAVOOSREQUEST']._serialized_end=475
  _globals['_CONSULTAVOOSRESPONSE']._serialized_start=477
  _globals['_CONSULTAVOOSRESPONSE']._serialized_end=580
  _globals['_VOOSSERVICE']._serialized_start=582
  _globals['_VOOSSERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
