// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/hotel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchHotelsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	City              string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	MinStars          int32                  `protobuf:"varint,2,opt,name=min_stars,json=minStars,proto3" json:"min_stars,omitempty"`
	MaxStars          int32                  `protobuf:"varint,3,opt,name=max_stars,json=maxStars,proto3" json:"max_stars,omitempty"`
	MinPrice          float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice          float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	AccommodationType string                 `protobuf:"bytes,6,opt,name=accommodation_type,json=accommodationType,proto3" json:"accommodation_type,omitempty"`
	OrderBy           string                 `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`                 // "price" or "rating"
	DelaySeconds      int32                  `protobuf:"varint,8,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"` // for performance testing
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchHotelsRequest) Reset() {
	*x = SearchHotelsRequest{}
	mi := &file_proto_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelsRequest) ProtoMessage() {}

func (x *SearchHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelsRequest.ProtoReflect.Descriptor instead.
func (*SearchHotelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *SearchHotelsRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *SearchHotelsRequest) GetMinStars() int32 {
	if x != nil {
		return x.MinStars
	}
	return 0
}

func (x *SearchHotelsRequest) GetMaxStars() int32 {
	if x != nil {
		return x.MaxStars
	}
	return 0
}

func (x *SearchHotelsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchHotelsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *SearchHotelsRequest) GetAccommodationType() string {
	if x != nil {
		return x.AccommodationType
	}
	return ""
}

func (x *SearchHotelsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *SearchHotelsRequest) GetDelaySeconds() int32 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

type SearchHotelsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hotels          []*Hotel               `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	HasAvailability bool                   `protobuf:"varint,2,opt,name=has_availability,json=hasAvailability,proto3" json:"has_availability,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchHotelsResponse) Reset() {
	*x = SearchHotelsResponse{}
	mi := &file_proto_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelsResponse) ProtoMessage() {}

func (x *SearchHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelsResponse.ProtoReflect.Descriptor instead.
func (*SearchHotelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotel_proto_rawDescGZIP(), []int{1}
}

func (x *SearchHotelsResponse) GetHotels() []*Hotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

func (x *SearchHotelsResponse) GetHasAvailability() bool {
	if x != nil {
		return x.HasAvailability
	}
	return false
}

type Hotel struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	City              string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Stars             int32                  `protobuf:"varint,4,opt,name=stars,proto3" json:"stars,omitempty"`
	Price             float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Available         bool                   `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	Amenities         []string               `protobuf:"bytes,7,rep,name=amenities,proto3" json:"amenities,omitempty"`
	AccommodationType string                 `protobuf:"bytes,8,opt,name=accommodation_type,json=accommodationType,proto3" json:"accommodation_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	mi := &file_proto_hotel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_proto_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *Hotel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Hotel) GetStars() int32 {
	if x != nil {
		return x.Stars
	}
	return 0
}

func (x *Hotel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Hotel) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *Hotel) GetAmenities() []string {
	if x != nil {
		return x.Amenities
	}
	return nil
}

func (x *Hotel) GetAccommodationType() string {
	if x != nil {
		return x.AccommodationType
	}
	return ""
}

var File_proto_hotel_proto protoreflect.FileDescriptor

const file_proto_hotel_proto_rawDesc = "" +
	"\n" +
	"\x11proto/hotel.proto\x12\x05hotel\"\x8c\x02\n" +
	"\x13SearchHotelsRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1b\n" +
	"\tmin_stars\x18\x02 \x01(\x05R\bminStars\x12\x1b\n" +
	"\tmax_stars\x18\x03 \x01(\x05R\bmaxStars\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12-\n" +
	"\x12accommodation_type\x18\x06 \x01(\tR\x11accommodationType\x12\x19\n" +
	"\border_by\x18\a \x01(\tR\aorderBy\x12#\n" +
	"\rdelay_seconds\x18\b \x01(\x05R\fdelaySeconds\"g\n" +
	"\x14SearchHotelsResponse\x12$\n" +
	"\x06hotels\x18\x01 \x03(\v2\f.hotel.HotelR\x06hotels\x12)\n" +
	"\x10has_availability\x18\x02 \x01(\bR\x0fhasAvailability\"\xd6\x01\n" +
	"\x05Hotel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05stars\x18\x04 \x01(\x05R\x05stars\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x06 \x01(\bR\tavailable\x12\x1c\n" +
	"\tamenities\x18\a \x03(\tR\tamenities\x12-\n" +
	"\x12accommodation_type\x18\b \x01(\tR\x11accommodationType2W\n" +
	"\fHotelService\x12G\n" +
	"\fSearchHotels\x12\x1a.hotel.SearchHotelsRequest\x1a\x1b.hotel.SearchHotelsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_hotel_proto_rawDescOnce sync.Once
	file_proto_hotel_proto_rawDescData []byte
)

func file_proto_hotel_proto_rawDescGZIP() []byte {
	file_proto_hotel_proto_rawDescOnce.Do(func() {
		file_proto_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hotel_proto_rawDesc), len(file_proto_hotel_proto_rawDesc)))
	})
	return file_proto_hotel_proto_rawDescData
}

var file_proto_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_hotel_proto_goTypes = []any{
	(*SearchHotelsRequest)(nil),  // 0: hotel.SearchHotelsRequest
	(*SearchHotelsResponse)(nil), // 1: hotel.SearchHotelsResponse
	(*Hotel)(nil),                // 2: hotel.Hotel
}
var file_proto_hotel_proto_depIdxs = []int32{
	2, // 0: hotel.SearchHotelsResponse.hotels:type_name -> hotel.Hotel
	0, // 1: hotel.HotelService.SearchHotels:input_type -> hotel.SearchHotelsRequest
	1, // 2: hotel.HotelService.SearchHotels:output_type -> hotel.SearchHotelsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hotel_proto_init() }
func file_proto_hotel_proto_init() {
	if File_proto_hotel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hotel_proto_rawDesc), len(file_proto_hotel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hotel_proto_goTypes,
		DependencyIndexes: file_proto_hotel_proto_depIdxs,
		MessageInfos:      file_proto_hotel_proto_msgTypes,
	}.Build()
	File_proto_hotel_proto = out.File
	file_proto_hotel_proto_goTypes = nil
	file_proto_hotel_proto_depIdxs = nil
}
